### ISSUE TITLE
api: create serverless api for runtime analysis

### ISSUE THREAD

**Issue by divy-work** [nestdotland/analyzer#22]
The runtime analysis is only possible in Deno so to use in the website some kind of API endpoint has to be exposed using vercel.

**Comment by maximousblk** [comment]
Vercel Serverless Functions support Deno and Rust as community supported runtimes

- [vercel-deno](https://github.com/TooTallNate/vercel-deno)
- [now-rust](https://github.com/mike-engel/now-rust)

**Comment by divy-work** [comment]
Yup, using vercel-deno would be enough

**Comment by divy-work** [comment]
Now online at https://analyzer.nest.land/
